# Generated by Django 4.2 on 2024-04-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flan',
            options={'verbose_name': 'flan', 'verbose_name_plural': 'flanes'},
        ),
    ]
