# Generated by Django 4.2 on 2024-04-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='customer_name',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
