# Generated by Django 4.2 on 2024-04-26 04:18

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default=autoslug.fields.AutoSlugField(unique=True)),
        ),
    ]
